### ISSUE TITLE
deprecated 'displot' dominates google

### ISSUE THREAD

**Issue by jabowery** [seaborn/seaborn.github.io#2]
google search for:

`seaborn histogram`

Produces a page about the deprecated 'displot' function.

**Comment by QuLogic** [comment]
`distplot` is [deprecated](https://seaborn.pydata.org/generated/seaborn.distplot.html), not `displot`.

**Comment by munael** [comment]
![image](https://user-images.githubusercontent.com/5769148/107477752-fed09300-6b80-11eb-8a65-878a9561703b.png)
`displot` is inaccessible on `0.11.1` :/
